"""
Django settings for facebook_integration project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

WSGI_APPLICATION = 'facebook_integration.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # Motor de base de datos (MySQL)
        'ENGINE': 'django.db.backends.mysql',
        
        # Nombre de la base de datos que creamos
        'NAME': 'facebook_integration_db',
        
        # Usuario de MySQL (por defecto 'root')
        'USER': 'root',
        
        # Contraseña de MySQL (CAMBIA ESTO por tu contraseña real)
        'PASSWORD': '',
        
        # Servidor donde está MySQL (local)
        'HOST': 'localhost',
        
        # Puerto por defecto de MySQL
        'PORT': '3306',
        
        # Opciones adicionales para el conector
        'OPTIONS': {
            'charset': 'utf8mb4',  # Soporte completo de Unicode
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Validación estricta
        },
    }
}

# APLICACIONES INSTALADAS
# Esta lista define qué módulos están activos en Django
INSTALLED_APPS = [
    # Aplicaciones integradas de Django:
    'django.contrib.admin',          # Panel de administración
    'django.contrib.auth',           # Sistema de autenticación
    'django.contrib.contenttypes',   # Gestión de tipos de contenido
    'django.contrib.sessions',       # Manejo de sesiones
    'django.contrib.messages',       # Sistema de mensajes
    'django.contrib.staticfiles',    # Archivos estáticos (CSS, JS, imágenes)
    
    # Aplicaciones de terceros:
    'rest_framework',                # Django REST Framework (para APIs)
    'corsheaders',                   # Manejo de CORS para peticiones externas
    
    # Nuestra aplicación personalizada:
    'social_app',                    # App que creamos para Facebook
]

# MIDDLEWARE (procesadores de peticiones)
# Asegúrate de que CorsMiddleware esté ANTES de CommonMiddleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← Agregar CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # <-- Esto es lo que falta
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]




# CONFIGURACIÓN DE CORS (permitir peticiones desde otros dominios)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Indica a Django dónde está el archivo de rutas principal
ROOT_URLCONF = 'facebook_integration.urls'

# Configuración básica de archivos estáticos
STATIC_URL = 'static/'

# Esquema de clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Validadores de contraseñas (opcional, pero recomendado)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# CONFIGURACIÓN DE FACEBOOK
# Aquí pondremos las credenciales que obtuvimos de Facebook Developers
FACEBOOK_APP_ID = '2  # ← Reemplaza con tu App ID real
FACEBOOK_APP_SECRET = ' # ← Reemplaza con tu App Secret
FACEBOOK_REDIRECT_URI = 'http://localhost:8000/facebook/callback/'

# IMPORTANTE: Nunca subas este archivo a repositorios públicos con credenciales reales
# En producción, usa variables de entorno:
# import os
# FACEBOOK_APP_ID = os.getenv('FACEBOOK_APP_ID')
# FACEBOOK_APP_SECRET = os.getenv('FACEBOOK_APP_SECRET')

# CONFIGURACIÓN DE ZONA HORARIA
TIME_ZONE = 'America/Hermosillo'  # Ajusta a tu zona horaria
USE_TZ = True

# CONFIGURACIÓN DE IDIOMA
LANGUAGE_CODE = 'es-mx'  # Español de México
